// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_VOLUME_BUTTON_LISTENER_G_H_
#define PIGEON_VOLUME_BUTTON_LISTENER_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace volume_button_listener {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class VolumeButtonListenerPlatformChannel;
  friend class VolumeButtonListenerCallbackChannel;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;
 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;
};

// Flutter -> Native
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class VolumeButtonListenerPlatformChannel {
 public:
  VolumeButtonListenerPlatformChannel(const VolumeButtonListenerPlatformChannel&) = delete;
  VolumeButtonListenerPlatformChannel& operator=(const VolumeButtonListenerPlatformChannel&) = delete;
  virtual ~VolumeButtonListenerPlatformChannel() {}
  virtual std::optional<FlutterError> StartListener() = 0;
  virtual std::optional<FlutterError> SetShowVolumeUi(bool show_volume_ui) = 0;
  virtual std::optional<FlutterError> StopListener() = 0;
  virtual ErrorOr<bool> IsListening() = 0;
  virtual ErrorOr<double> GetVolume() = 0;
  virtual std::optional<FlutterError> SetVolume(double volume) = 0;

  // The codec used by VolumeButtonListenerPlatformChannel.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `VolumeButtonListenerPlatformChannel` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    VolumeButtonListenerPlatformChannel* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    VolumeButtonListenerPlatformChannel* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  VolumeButtonListenerPlatformChannel() = default;
};
// Native -> Flutter
//
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class VolumeButtonListenerCallbackChannel {
 public:
  VolumeButtonListenerCallbackChannel(flutter::BinaryMessenger* binary_messenger);
  VolumeButtonListenerCallbackChannel(
    flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const flutter::StandardMessageCodec& GetCodec();
  void OnVolumeButtonPressed(
    bool is_volume_up,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnVolumeButtonReleased(
    bool is_volume_up,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
 private:
  flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace volume_button_listener
#endif  // PIGEON_VOLUME_BUTTON_LISTENER_G_H_
