// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class VolumeButtonListenerPigeonCodecReader: FlutterStandardReader {
}

private class VolumeButtonListenerPigeonCodecWriter: FlutterStandardWriter {
}

private class VolumeButtonListenerPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return VolumeButtonListenerPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return VolumeButtonListenerPigeonCodecWriter(data: data)
  }
}

class VolumeButtonListenerPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = VolumeButtonListenerPigeonCodec(readerWriter: VolumeButtonListenerPigeonCodecReaderWriter())
}

/// Flutter -> Native
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol VolumeButtonListenerPlatformChannel {
  func startListener() throws
  func setShowVolumeUi(showVolumeUi: Bool) throws
  func stopListener() throws
  func isListening() throws -> Bool
  func getVolume() throws -> Double
  func setVolume(volume: Double) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VolumeButtonListenerPlatformChannelSetup {
  static var codec: FlutterStandardMessageCodec { VolumeButtonListenerPigeonCodec.shared }
  /// Sets up an instance of `VolumeButtonListenerPlatformChannel` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VolumeButtonListenerPlatformChannel?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startListenerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.volume_button_listener.VolumeButtonListenerPlatformChannel.startListener\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startListenerChannel.setMessageHandler { _, reply in
        do {
          try api.startListener()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startListenerChannel.setMessageHandler(nil)
    }
    let setShowVolumeUiChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.volume_button_listener.VolumeButtonListenerPlatformChannel.setShowVolumeUi\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setShowVolumeUiChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let showVolumeUiArg = args[0] as! Bool
        do {
          try api.setShowVolumeUi(showVolumeUi: showVolumeUiArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setShowVolumeUiChannel.setMessageHandler(nil)
    }
    let stopListenerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.volume_button_listener.VolumeButtonListenerPlatformChannel.stopListener\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopListenerChannel.setMessageHandler { _, reply in
        do {
          try api.stopListener()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopListenerChannel.setMessageHandler(nil)
    }
    let isListeningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.volume_button_listener.VolumeButtonListenerPlatformChannel.isListening\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isListeningChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isListening()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isListeningChannel.setMessageHandler(nil)
    }
    let getVolumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.volume_button_listener.VolumeButtonListenerPlatformChannel.getVolume\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getVolumeChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getVolume()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getVolumeChannel.setMessageHandler(nil)
    }
    let setVolumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.volume_button_listener.VolumeButtonListenerPlatformChannel.setVolume\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setVolumeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let volumeArg = args[0] as! Double
        do {
          try api.setVolume(volume: volumeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setVolumeChannel.setMessageHandler(nil)
    }
  }
}
/// Native -> Flutter
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol VolumeButtonListenerCallbackChannelProtocol {
  func onVolumeButtonPressed(isVolumeUp isVolumeUpArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onVolumeButtonReleased(isVolumeUp isVolumeUpArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class VolumeButtonListenerCallbackChannel: VolumeButtonListenerCallbackChannelProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: VolumeButtonListenerPigeonCodec {
    return VolumeButtonListenerPigeonCodec.shared
  }
  func onVolumeButtonPressed(isVolumeUp isVolumeUpArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.volume_button_listener.VolumeButtonListenerCallbackChannel.onVolumeButtonPressed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([isVolumeUpArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onVolumeButtonReleased(isVolumeUp isVolumeUpArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.volume_button_listener.VolumeButtonListenerCallbackChannel.onVolumeButtonReleased\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([isVolumeUpArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
